### PR TITLE
Label links to other notebooks as "Chapter" rather than "Section".

### PR DESCRIPTION
**Pull request by ketch**
Perhaps this should be a configurable option.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks; yes, it probably should be configurable. I'm happy to merge this for now if you fix the test, though.

**Comment by ketch** [comment]
Done!

**Comment by takluyver** [comment]
Thanks

**Comment by takluyver** [comment]
I opened issue #10 for the follow up about configuring them.

**Pull request merged**
